= top

== user API

=== 회원 가입

operation::user-controller-test/create-member_success[snippets="http-request,http-response"]

=== 이메일 중복 확인

operation::user-controller-test/check-duplicate-email_success[snippets="http-request,http-response"]

=== 닉네임 중복 확인

operation::user-controller-test/check-duplicate-nickname_success[snippets="http-request,http-response"]

=== 회원 정보 수정

operation::user-controller-test/update-user_success[snippets="http-request,http-response"]

=== 비밀번호 변경

operation::user-controller-test/update-password_success[snippets="http-request,http-response"]

=== 회원 탈퇴

operation::user-controller-test/delete[snippets="http-request,http-response"]

== auth API

=== 로그인

operation::user-controller-test/login_success[snippets="http-request,http-response"]

=== 이메일 인증코드 전송

operation::user-controller-test/send-verification-code_success[snippets="http-request,http-response"]

=== 이메일 인증코드 확인

operation::user-controller-test/verify-email_success[snippets="http-request,http-response"]